export const START_FETCHING_LISTS_GROUP =
  "redux/lists/START_FETCHING_LISTS_GROUP";
export const SUCCESS_FETCHING_LISTS_GROUP =
  "redux/lists/SUCCESS_FETCHING_LISTS_GROUP";
export const ERROR_FETCHING_LISTS_GROUP =
  "redux/lists/ERROR_FETCHING_LISTS_GROUP";
